app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
