# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@a
    placeUpdateListener:
        class: AppBundle\EventListener\updateModifierUser
        arguments: ["@security.token_storage"]
        tags:
          - { name: doctrine.event_listener, event : prePersist}
    getData:
        class: AppBundle\Command\GetData
        arguments: ["@doctrine.orm.entity_manager"]
    httpcatFilter:
        class: AppBundle\Twig\AppExtension
        tags:
            - { name: twig.extension }
